### ISSUE TITLE
Possible API issues?

### ISSUE THREAD

**Issue by jackkelly-bayliss** [dhondtlaurens/covid19#2]
Hello,

I've been receiving this error since commit https://github.com/dhondtlaurens/covid19/commit/46bb59c11ce726d9d732e40bcfc0d2ff68c26fd0 - is this an issue on my side or the API's side? Thank you.

`Access to fetch at 'https://covid19-data-api.herokuapp.com/countries/22_03_20' from origin 'https://mydomain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Kind Regards,
Jack

**Comment by dhondtlaurens** [comment]
Hi Jack,

Is this while developing on a fork? My API currently has CORS settings to only work with my two domains to protect it from external abuse. I could add you to the whitelist!

Kind regards,
Laurens

**Comment by dhondtlaurens** [comment]
For development, it will fallback on local files.
