### ISSUE TITLE
Option to compare from day-zero

### ISSUE THREAD

**Issue by fernandocarletti** [dhondtlaurens/covid19#3]
Hello. It may be a good addition to the compare graph to allow a view from the first reported case. WDYT?

**Comment by dhondtlaurens** [comment]
Hi @fernandocarletti 

This feature has been requested by multiple people! This has been resolved in my latest commit (https://github.com/dhondtlaurens/covid19/commit/5a0c0d25f96b5a014cac3366acace20176df5547)

Kind regards,
Laurens

**Comment by fernandocarletti** [comment]
Awesome!! Thank you!
